/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ImovelDAO;
import DAO.ProprietarioDAO;
import Model.Imovel;
import Model.Proprietario;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class CadImovel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadImovel.class.getName());

    // DAOs - criados uma vez, reutilizados em todos os métodos
    private final ImovelDAO imovelDAO = new ImovelDAO();
    private final ProprietarioDAO proprietarioDAO = new ProprietarioDAO();

    // Recebidos via construtor
    private final Usuario usuarioLogado;
    private Imovel imovelEmEdicao;         // null = modo cadastro novo; preenchido = modo edição/exclusão
    private final TelaBuscaPro telaOrigem; // pode ser null, se a tela for aberta sem vir de lá

    // Descoberto dentro do formWindowOpened, a partir do usuarioLogado
    private Proprietario proprietario;

    /**
     * Creates new form CadImovel
     */
    public CadImovel(Usuario usuarioLogado, Imovel imovelSelecionado, TelaBuscaPro telaOrigem) {
        this.usuarioLogado = usuarioLogado;
        this.imovelEmEdicao = imovelSelecionado;
        this.telaOrigem = telaOrigem;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescri = new javax.swing.JTextArea();
        cbTipo = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("Cadastro Imóveis");

        txtDescri.setColumns(20);
        txtDescri.setRows(5);
        jScrollPane1.setViewportView(txtDescri);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluguel", "Venda", " " }));
        cbTipo.addActionListener(this::cbTipoActionPerformed);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Indisponivel", " " }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel3.setText("Status");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel4.setText("Descrição");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel5.setText("Preço");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel6.setText("Tipo");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel7.setText("Endereço");

        txtPreco.addActionListener(this::txtPrecoActionPerformed);

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(this::btnCadActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        String descricao = txtDescri.getText().trim();
        String endereco = txtEndereco.getText().trim();
        String precoTexto = txtPreco.getText().trim();

        if (descricao.isEmpty() || endereco.isEmpty() || precoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! por favor, preencha todos os campos obrigatórios!");
            return;
        }

        try {
            double preco = Double.parseDouble(precoTexto.replace(",", "."));

            Imovel novoImovel = new Imovel(
                    0,
                    proprietario.getIdProprietario(),
                    descricao,
                    cbTipo.getSelectedItem().equals("Venda"),
                    preco,
                    endereco,
                    cbStatus.getSelectedItem().equals("Disponível")
            );

            boolean sucesso = imovelDAO.cadastrar(novoImovel);

            if (!sucesso) {
                JOptionPane.showMessageDialog(this, "Não foi possível cadastrar o imóvel.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Imóvel cadastrado com sucesso!");
            limparCampos();

            if (telaOrigem != null) {
                telaOrigem.atualizarTabela();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! digite um valor numérico válido no campo Preço!");
        }
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       System.out.println(">>> Botão Editar clicado!");
    System.out.println(">>> imovelEmEdicao = " + imovelEmEdicao);

    if (imovelEmEdicao == null) {
        JOptionPane.showMessageDialog(this, "Opa, algo deu errado! nenhum imóvel selecionado para editar!");
        return;
    }

    String descricao = txtDescri.getText().trim();
    String endereco = txtEndereco.getText().trim();
    String precoTexto = txtPreco.getText().trim();

    System.out.println(">>> descricao=[" + descricao + "] endereco=[" + endereco + "] preco=[" + precoTexto + "]");

    if (descricao.isEmpty() || endereco.isEmpty() || precoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Opa, algo deu errado! por favor, preencha todos os campos obrigatórios!");
        return;
    }

    try {
        double preco = Double.parseDouble(precoTexto.replace(",", "."));

        imovelEmEdicao.setDescricao(descricao);
        imovelEmEdicao.setEndereco(endereco);
        imovelEmEdicao.setPreco(preco);
        imovelEmEdicao.setTipo(cbTipo.getSelectedItem().equals("Venda"));
        imovelEmEdicao.setStatus(cbStatus.getSelectedItem().equals("Disponível"));

        System.out.println(">>> Chamando imovelDAO.alterar() para id=" + imovelEmEdicao.getIdImovel());

        boolean sucesso = imovelDAO.alterar(imovelEmEdicao);

        System.out.println(">>> Resultado do alterar(): " + sucesso);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Não foi possível atualizar o imóvel.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Imóvel atualizado com sucesso!");
        limparCampos();

        if (telaOrigem != null) {
            telaOrigem.atualizarTabela();
        }
        this.dispose();

    } catch (NumberFormatException e) {
        System.out.println(">>> Erro de conversão numérica: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Opa, algo deu errado! digite um valor numérico válido no campo Preço!");
    }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        System.out.println(">>> Botão Excluir clicado!");
        
        if (imovelEmEdicao == null) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! nenhum imóvel selecionado para excluir!");
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Excluir o imóvel \"" + imovelEmEdicao.getDescricao() + "\"?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        boolean sucesso = imovelDAO.excluir(imovelEmEdicao.getIdImovel());

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Não foi possível excluir o imóvel.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Imóvel excluído com sucesso!");
        limparCampos();

        if (telaOrigem != null) {
            telaOrigem.atualizarTabela();
        }
        this.dispose();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        System.out.println(">>> formWindowOpened da CadImovel RODOU!");
        if (usuarioLogado == null) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! nenhum usuário logado foi informado!");
            this.dispose();
            return;
        }

        proprietario = proprietarioDAO.buscarPorIdUsu(usuarioLogado.getId());

        if (proprietario == null) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! usuário logado não é um proprietário cadastrado!");
            this.dispose();
            return;
        }

        if (imovelEmEdicao != null) {
            preencherFormulario(imovelEmEdicao);
        }
    }//GEN-LAST:event_formWindowOpened

    private void preencherFormulario(Imovel imovel) {
        txtDescri.setText(imovel.getDescricao());
        txtEndereco.setText(imovel.getEndereco());
        txtPreco.setText(String.valueOf(imovel.getPreco()));
        cbTipo.setSelectedItem(imovel.getTipoDescricao());
        cbStatus.setSelectedItem(imovel.getStatusDescricao());
    }

    private void limparCampos() {
        txtDescri.setText("");
        txtEndereco.setText("");
        txtPreco.setText("");
        cbTipo.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        imovelEmEdicao = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Usuario usuarioLogado = new Usuario();
        Imovel imovelSelecionado = new Imovel();
        TelaBuscaPro telaOrigem = null;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadImovel(usuarioLogado, imovelSelecionado, telaOrigem).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescri;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
