/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.AdministradorDAO;
import DAO.ClienteDAO;
import DAO.ProprietarioDAO;
import DAO.UsuarioDAO;
import Model.Administrador;
import Model.Cliente;
import Model.Proprietario;
import Model.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class TelaADM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaADM.class.getName());

    /**
     * Creates new form TelaADM
     */
    public TelaADM() {
        initComponents();
    }
    private List<? extends Usuario> usuariosCarregados;   // guarda o objeto Usuario completo de cada linha
    private List<String> papeisCarregados;
    private final UsuarioDAO usuarioDAO = new UsuarioDAO();
    private final AdministradorDAO administradorDAO = new AdministradorDAO();
    private final ProprietarioDAO proprietarioDAO = new ProprietarioDAO();
    private final ClienteDAO clienteDAO = new ClienteDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsu = new javax.swing.JTable();
        cbPapel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCadUsu = new javax.swing.JButton();
        btnEditarUsu = new javax.swing.JButton();
        btnExcluirUsu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        jLabel2.setText("Tela Administrador");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        tbUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Papel"
            }
        ));
        tbUsu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbUsuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsu);

        cbPapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Proprietário", "Administrador" }));
        cbPapel.addItemListener(this::cbPapelItemStateChanged);
        cbPapel.addActionListener(this::cbPapelActionPerformed);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel5.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel7.setText("Papel");

        btnCadUsu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnCadUsu.setText("Cadastrar usuário");
        btnCadUsu.addActionListener(this::btnCadUsuActionPerformed);

        btnEditarUsu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnEditarUsu.setText("Editar Usuário");
        btnEditarUsu.addActionListener(this::btnEditarUsuActionPerformed);

        btnExcluirUsu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnExcluirUsu.setText("Excluir Usuário");
        btnExcluirUsu.addActionListener(this::btnExcluirUsuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNome)
                        .addComponent(txtEmail)
                        .addComponent(txtSenha)
                        .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadUsu)
                    .addComponent(btnEditarUsu)
                    .addComponent(btnExcluirUsu))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregarTabela();
    }

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cbPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPapelActionPerformed

    private void tbUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuMouseClicked
        Usuario selecionado = usuarioSelecionado();
        if (selecionado == null) {
            return;
        }

        txtNome.setText(selecionado.getNome());
        txtEmail.setText(selecionado.getEmail());
        txtTel.setText(selecionado.getTelefone());
        txtSenha.setText("");

        int linha = tbUsu.getSelectedRow();
        cbPapel.setSelectedItem(papeisCarregados.get(linha));

    }//GEN-LAST:event_tbUsuMouseClicked

    private void btnCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuActionPerformed
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = txtSenha.getText().trim();
        String telefone = txtTel.getText().trim();
        String papel = (String) cbPapel.getSelectedItem();

        if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! por favor, preencha todos os campos obrigatórios!");
            return;
        }

        Usuario novoUsuario = new Usuario(0, nome, email, senha, telefone);
        usuarioDAO.cadastrar(novoUsuario);

        switch (papel) {
            case "Cliente" ->
                clienteDAO.cadastrar(new Cliente(0, novoUsuario));
            case "Proprietário" ->
                proprietarioDAO.cadastrar(new Proprietario(0, novoUsuario));
            case "Administrador" ->
                administradorDAO.cadastrar(new Administrador(0, novoUsuario));
            default -> {
                JOptionPane.showMessageDialog(this, "Papel inválido!");
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Usuário " + novoUsuario.getNome() + " cadastrado com sucesso!");

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnCadUsuActionPerformed


    private void btnEditarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuActionPerformed
        Usuario selecionado = usuarioSelecionado();

        if (selecionado == null) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! selecione um usuário na tabela!");
            return;
        }

        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = txtSenha.getText().trim();
        String telefone = txtTel.getText().trim();

        if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! por favor, preencha todos os campos obrigatórios!");
            return;
        }

        selecionado.setNome(nome);
        selecionado.setEmail(email);
        selecionado.setSenha(senha);
        selecionado.setTelefone(telefone);

        boolean sucesso = usuarioDAO.alterar(selecionado);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Não foi possível atualizar. Esse e-mail já está em uso por outro usuário!");
            return;
        }

        JOptionPane.showMessageDialog(this, "Usuário " + selecionado.getNome() + " atualizado com sucesso!");

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnEditarUsuActionPerformed

    private void btnExcluirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuActionPerformed
        Usuario selecionado = usuarioSelecionado();
        if (selecionado == null) {
            JOptionPane.showMessageDialog(this, "Opa, algo deu errado! selecione um usuário na tabela!");
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Excluir o usuário " + selecionado.getNome() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        String papel = (String) cbPapel.getSelectedItem();

        if (selecionado instanceof Cliente c) {
            clienteDAO.excluir(c.getIdCliente());
        } else if (selecionado instanceof Proprietario p) {
            proprietarioDAO.excluir(p.getIdProprietario());
        } else if (selecionado instanceof Administrador a) {
            administradorDAO.excluir(a.getIdAdm());
        }

        usuarioDAO.excluir(selecionado.getId());

        JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnExcluirUsuActionPerformed

    private void tbUsuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbUsuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbUsuAncestorAdded

    private void cbPapelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPapelItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            carregarTabela();
        }
    }//GEN-LAST:event_cbPapelItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaADM().setVisible(true));
    }

    private void carregarTabela() {
        String papel = (String) cbPapel.getSelectedItem();

        switch (papel) {
            case "Cliente" ->
                usuariosCarregados = clienteDAO.listarTodos();
            case "Proprietário" ->
                usuariosCarregados = proprietarioDAO.listarTodos();
            case "Administrador" ->
                usuariosCarregados = administradorDAO.listarTodos();
            default -> {
                JOptionPane.showMessageDialog(this, "Opa, algo deu errado! papel inválido selecionado!");
                return;
            }
        }

        DefaultTableModel modelo = (DefaultTableModel) tbUsu.getModel();
        modelo.setRowCount(0);

        for (Usuario u : usuariosCarregados) {
            modelo.addRow(new Object[]{u.getNome(), u.getEmail(), u.getTelefone()});
        }
    }

    private Usuario usuarioSelecionado() {
        int linha = tbUsu.getSelectedRow();
        if (linha == -1 || usuariosCarregados == null || linha >= usuariosCarregados.size()) {
            return null;
        }
        return usuariosCarregados.get(linha);
    }

    private void limparCampos() {
        txtNome.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtTel.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadUsu;
    private javax.swing.JButton btnEditarUsu;
    private javax.swing.JButton btnExcluirUsu;
    private javax.swing.JComboBox<String> cbPapel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
